# spring
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://weibin268.top:3306/upms?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: zhuang
    password: 123456

# logging
logging:
  level:
    org.springframework.jdbc.datasource.DataSourceTransactionManager: debug
    org.springframework.jdbc.datasource.DataSourceUtils: debug